#!/bin/bash

if [[ $# -ne "1" ]];then
	echo "Usage: $0 <pause|resume>"
	exit 1;
fi

if [[ "$1" == "pause" ]];then
	sudo killall -STOP NetworkManager
	echo "NetworkManager paused"
elif [[ "$1" == "resume" ]];then
	sudo killall -CONT NetworkManager
	sudo service NetworkManager restart
	echo "NetworkManager resumed"
else
	echo "Usage: $0 <pause|resume>"
	exit 1;
fi
