#!/bin/bash

usage() {
	echo "Usage: $0 <start|stop>"
}


if [ $# -eq 0 ]; then
	usage
	exit 1
fi

if [ "$1" ==  "start" ]; then
	ps -e | grep -i openconnect > /dev/null
	exit_code=$?
	if [ $exit_code -ne 0 ] ; then
		sudo openconnect --protocol=nc -b -c <certificate> <server> 
	else
		echo "An OpenConnect instance is already running."
	fi
elif [ "$1" ==  "stop" ]; then
	sudo pkill openconnect
	sudo systemctl restart network-manager
else
  usage
fi
